intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

lib{crails-xml-parser}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

cxx.poptions =+  "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-xml-parser}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{crails-xml-parser}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-xml-parser}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-xml-parser}: bin.lib.version = "-$version.project_id"
else
  lib{crails-xml-parser}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/crails/request_parsers
  install.subdirs = true
}
